In [3]:
import numpy as np

**1D Array**

In [4]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


**2D Array**

In [5]:
arr = np.array([[1, 2, 3],[4, 5, 6]])
print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.dtype)
print(arr.size)
print(arr.itemsize)

[[1 2 3]
 [4 5 6]]
(2, 3)
2
int64
6
8


**3D Array**

In [6]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[0])
print(arr[1])
print(arr[0,0])
print(arr[0,1])
print(arr[1,0])
print(arr[1,1])

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]


### array index

**access 1D Array**

In [7]:
arr = np.array([1, 2, 3, 4])
print(arr[0])
print(arr[1])
print(arr[2]+arr[3])

1
2
7


**access 2D Array**

In [8]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('2nd element on 1st row: ', arr[0, 1])
print('5th element on 2nd row: ', arr[1, 4]) 

2nd element on 1st row:  2
5th element on 2nd row:  10


**access 3D Array**

In [9]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[0,0])
print(arr[0,1])
print(arr[:,1])
print(arr[:,0,:])
print(arr[:,1,0])
print(arr[:,1,1])
print(arr[:,1,2])
print(arr[:,1,:])#3d array

[1 2 3]
[4 5 6]
[[ 4  5  6]
 [10 11 12]]
[[1 2 3]
 [7 8 9]]
[ 4 10]
[ 5 11]
[ 6 12]
[[ 4  5  6]
 [10 11 12]]


**negative indexing**

In [10]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('Last element of 2nd dim:', arr[1, -1])

Last element of 2nd dim: 10


### array slicing __[:]__

In [11]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5])
print(arr[4:])
print(arr[:4])#not included

[2 3 4 5]
[5 6 7]
[1 2 3 4]


**negative slicing**

In [12]:
print(arr[-3:-1])

[5 6]


**step determines the step of the slicing**

In [13]:
print(arr[1:5:2])
print(arr[::2])

[2 4]
[1 3 5 7]


**slice 2D Array**

In [14]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1, 1:4])
print(arr[0:2, 2])
print(arr[0:1, :])
print(arr[0:1, 1])

[7 8 9]
[3 8]
[[1 2 3 4 5]]
[2]


### data types

In [15]:
arr = np.array([1, 2, 3, 4])
print(arr.dtype)
arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)
arr = np.array([1,2,3,4], dtype='S')
print(arr.dtype)
arr = np.array([1, 2, 3, 4], dtype='i4')
print(arr.dtype)
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)
arr = np.array([1, 0, 3])
newarr = arr.astype(bool)
print(newarr)
print(newarr.dtype)

int64
<U6
|S1
int32
[1 2 3]
int32
[ True False  True]
bool


### Copy vs View

In [16]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
y = arr.view()
arr[0] = 42
x[1] = 43
y[2] = 44
print(arr)
print(x)
print(y)
print(x.base)
print(y.base)

[42  2 44  4  5]
[ 1 43  3  4  5]
[42  2 44  4  5]
None
[42  2 44  4  5]


### the shape of an array

In [17]:
arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8]])
print(arr.shape)

(2, 4)


In [18]:
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


**by shaping, we can change the number of elements in each dimension**

In [19]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


**reshape from 1D to 3D**

In [20]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
print(newarr)
print(newarr.base)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


**you are allowed to have one "unknown" dimension**

In [21]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(2, 2, -1)
print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


**flattening array means converting a multidimensional array into a 1D array**

In [22]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]


### Array Iterating

In [23]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [24]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


In [25]:
arr = np.array([1, 2, 3])
for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
    print(x)

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')


**iterate through every scalar element of the 2D array skipping 1 element**

In [26]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for x in np.nditer(arr[:, ::2]):
    print(x)

1
3
5
7


**enumeration means mentioning sequence number of somethings one by one**

In [27]:
arr = np.array([1, 2, 3])
for idx, x in np.ndenumerate(arr):
    print(idx, x)

(0,) 1
(1,) 2
(2,) 3


**enumerate on 2D array's elements**

In [28]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
for idx, x in np.ndenumerate(arr):
    print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


### join array

In [29]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


**join two 2D arrays along rows (axis=1)**

In [30]:
arr1 = np.array([[1, 2],[3, 4]])
arr2 = np.array([[5, 6],[7, 8]])
arr = np.concatenate((arr1, arr2), axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


**putting them one over the other, ie. stacking**

In [31]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2), axis=1)
print(arr)

[[1 4]
 [2 5]
 [3 6]]


### Stack

**stack along rows**

In [32]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.hstack((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


**stack along columns**

In [33]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.vstack((arr1, arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


**stack along height, which is the same as depth**

In [34]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.dstack((arr1, arr2))
print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


### split

In [35]:
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr)
print(np.array_split(arr, 4))

[array([1, 2]), array([3, 4]), array([5, 6])]
[array([1, 2]), array([3, 4]), array([5]), array([6])]


**split one 2D array into three 2D arrays**

In [36]:
arr = np.array([[1, 2],[3, 4],[5, 6],[7, 8],[9, 10],[11,12]])
newarr = np.array_split(arr, 3)
print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


**split the 2D array into three 2D arrays along columns**

In [37]:
arr = np.array([[1,2,3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.array_split(arr, 3, axis=1)
print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


**hsplit the 2D array into three 2D arrays along columns**

In [38]:
newarr = np.hsplit(arr, 3)
print(newarr) 

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


### search

**search an array for a certain value, and return the indexes that get a match**

In [39]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr==4)
print(x)

(array([3, 5, 6]),)


In [40]:
x = np.where(arr%2==1)
print(x)

(array([0, 2, 4]),)


**a method called searchsorted() which performs a binary search in the array, and return the index where the specified value would be inserted into maintain the search order**

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print(np.searchsorted(arr, 7))
arr = np.array([6, 7, 8, 9])
print(np.searchsorted(arr, 7))
print(np.searchsorted(arr, 7, side='right'))

In [48]:
arr = np.array([6, 7, 8, 9])
print(np.searchsorted(arr, [2,4,6]))
arr = np.array([1, 3, 5, 7])
print(np.searchsorted(arr, [2,4,6]))

[0 0 0]
[1 2 3]


### Sort

In [ ]:
arr = np.array([3,2,0,1])
print(np.sort(arr))

In [51]:
arr = np.array(['banana', 'cherry', 'apple'])
print(np.sort(arr)) 

['apple' 'banana' 'cherry']


In [ ]:
arr = np.array([True, False, True])
print(np.sort(arr)) 

In [53]:
arr = np.array([[3,2,4],[5,0,1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


### Filter

**getting some elements out of an existing array and creating a new array out of them is called filtering**


**In Numpy, you filter an array using a boolean index list**

In [54]:
arr = np.array([41, 42, 43, 44])
x = [True, False, True, False]
newarr = arr[x]
print(newarr)

[41 43]


In [56]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
filter_arr = []
for element in arr:
    if element % 2 == 0:
        filter_arr.append(True)
    else:
        filter_arr.append(False)
print(filter_arr)
newarr = arr[filter_arr]
print(newarr)

[False, True, False, True, False, True, False]
[2 4 6]


**create filter directly from array**

In [ ]:
arr = np.array([41, 42, 43, 44])
filter_arr = arr > 42
print(filter_arr)
newarr = arr[filter_arr]
print(newarr)

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
filter_arr = arr % 2 == 0
print(filter_arr)
newarr = arr[filter_arr]
print(newarr)